image: "debian:sid"

before_script:
  - apt update
  - apt install -y python3 python3-dev python3-pip watchman
  - python3 --version
  - pip3 install poetry
  - poetry install


stages:
  - Code Analysis


flake8:
  stage: Code Analysis
  script:
    - flake8 --max-line-length=120 toy/*.py
