version: '3'
services:
    mongodb:
        image: mongo
        container_name: toy-mongodb
        volumes:
            - ../deployment/toy/mongodb/data/db:/data/db
            - /etc/localtime:/etc/localtime:ro
        restart: always
        networks:
            - default
 
    web:
        build: .
        image: toy-image
        container_name: toy-web
        volumes:
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 9000:9000
        links:
            - mongodb
        networks:
            - default
        restart: always
        environment:
            TOY_SETTINGS: /app/toy-production.cfg
        command:
            uwsgi --lazy-apps --ini scripts/toy-uwsgi.ini
        logging:
            options:
                max-size: "10m"
                max-file: "3"
    

networks:
    default:
